### ISSUE TITLE
This is not working

### ISSUE THREAD

**Issue by UpsideBottom** [Catalyst-42/SSRPGS#1]
I'm a windows 11 (x64) user. I'm new to GitHub and Python as-well.
I tried three options, but none of them worked :(
> SSRPGS_Windows_v1.0.0.zip

I downloaded the file, extracted, ran the exe. Then after I opened my "save.txt"(Exported from Mobile), it takes a refresh and nothing changes.
> Launching Editor

As far I guess, I did all as said in the documentation. But after I run "python3 editor.py" in "/src" directory, the error is shown:
![error in cmd](https://github.com/user-attachments/assets/7e70af2a-ef9e-4e9b-a5f7-f5cf5fddc70f)
> Making a Build

After running "pip install pyinstaller setuptools" in cmd, I opened ran "setup.bat" inside "build" folder and this error shows up: 
![Unhandled exception in script](https://github.com/user-attachments/assets/a0cb9b9a-2599-4846-ac48-c98284a9e018)
As making my first issue in GitHub, sorry if I did something in-appropriate. Please help me if I'm doing something wrong.

**Comment by Catalyst-42** [comment]
Are you sure you have installed the dependencies? It's like there aren't any. 

`pip install -r requirements.txt`

**Comment by UpsideBottom** [comment]
> Are you sure you have installed the dependencies? It's like there aren't any.
> 
> `pip install -r requirements.txt`

yeah, I did

**Comment by Catalyst-42** [comment]
Can you tell me what you have displayed when you call `pip freeze`

**Comment by UpsideBottom** [comment]
> Can you tell me what you have displayed when you call `pip freeze`

![pip freeze](https://github.com/user-attachments/assets/369cb7bc-e2df-4cab-8087-f7f0c16b5158)

**Comment by Catalyst-42** [comment]
What about the .exe version, when you open selecting a file to edit it just starts an endless download, right?

**Comment by Catalyst-42** [comment]
Try by this [discussion ](https://github.com/hoffstadt/DearPyGui/issues/1822) install [last Visual C++](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170). I'm trying to replicate your error on windows 10, but everything works smoothly for me :(

**Comment by Catalyst-42** [comment]
And you can also try to open this test file in exe editor
[primary_save.txt](https://github.com/user-attachments/files/17720281/primary_save.txt)

**Comment by Catalyst-42** [comment]
In general, the version should not affect performance. Can you attach your save file for me to look at it for myself?

**Comment by UpsideBottom** [comment]
The [updated v1.1.0](https://github.com/Catalyst-42/SSRPGS/releases/tag/v1.1.0) version works fine.

**Comment by UpsideBottom** [comment]
> Try by this [discussion ](https://github.com/hoffstadt/DearPyGui/issues/1822) install [last Visual C++](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170). I'm trying to replicate your error on windows 10, but everything works smoothly for me :(

I installed MSVisualC++. Now the build works.
But the running "python3 editor.py" in "/src" is giving me the same error :/

**Comment by Catalyst-42** [comment]
I think so, if the .exe version is working properly

**Comment by UpsideBottom** [comment]
Ok, then. **Thank you** so much for your help.❤️
